### ISSUE TITLE
App crashes instantly when calling scan()

### ISSUE THREAD

**Issue by dasgib** [tjwoon/csZBar#12]
I've tested on various devices (Android 4.4.4, 4.4.3 and 5.0.2), when I call cloudSky.zbar.scan() the app immediately crashes. Looks like iconv cannot be loaded.

Here's the logcat:

Class init failed in newInstance call (Lorg/cloudsky/cordovaPlugins/ZBarScannerActivity;)
D/AndroidRuntime( 5388): Shutting down VM
W/dalvikvm( 5388): threadid=1: thread exiting with uncaught exception (group=0x41611d40)
E/AndroidRuntime( 5388): FATAL EXCEPTION: main
E/AndroidRuntime( 5388): Process: com.ionicframework.myapp119689, PID: 5388
E/AndroidRuntime( 5388): java.lang.UnsatisfiedLinkError: **Couldn't load iconv from loader** dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ionicframework.myapp119689-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.ionicframework.myapp119689-1, /vendor/lib, /system/lib]]]: findLibrary returned null
E/AndroidRuntime( 5388): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime( 5388): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime( 5388): 	at org.cloudsky.cordovaPlugins.ZBarScannerActivity.<clinit>(ZBarScannerActivity.java:68)

**Comment by dasgib** [comment]
Resolved: copy content from platforms/android/libs/* to platforms/android/src/main/jniLibs/
