### ISSUE TITLE
Galaxy S6 Crashes

### ISSUE THREAD

**Issue by rubensayshi** [tjwoon/csZBar#35]
I'm getting a few crash reports (in google play console), but don't have a device to reproduce it myself and I don't understand the trace either.

Figured I'd put it up here to find out if this is something that is your concern and/or aware of this or just something I did wrong etc.

```
Android 5.1
Galaxy S6 Edge (zerolte)
Galaxy S6 (zeroflte)
Galaxy S6 Edge (zeroltetmo)
Galaxy S6 (zerofltetmo)
```

```
Android 5.0
c218v13_jbaol_3m_fhd_elephone
HTC ONE M8s (htc_m8qlul)
Yureka (YUREKA)
```

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.blocktrail.mywallet-1/base.apk"],nativeLibraryDirectories=[/data/app/com.blocktrail.mywallet-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libiconv.so"
    at java.lang.Runtime.loadLibrary(Runtime.java:366)
    at java.lang.System.loadLibrary(System.java:988)
    at org.cloudsky.cordovaPlugins.ZBarScannerActivity.<clinit>(ZBarScannerActivity.java:77)
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at java.lang.Class.newInstance(Class.java:1684)
    at android.app.Instrumentation.newActivity(Instrumentation.java:1080)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2954)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
    at android.app.ActivityThread.access$1000(ActivityThread.java:198)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6837)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by rubensayshi** [comment]
I found some stuff about this particular crash for people who are using zbar in a normal android app

**Comment by rubensayshi** [comment]
Okay I guess it wasn't that hard to figure out, there's no `libzbarjni.so` in `x86_64`

**Comment by dcousens** [comment]
@rubensayshi did you end up resolving this?

**Comment by rubensayshi** [comment]
hmm, I dont think so :/

guess I somehow forgot that I still had this bug around :/

**Comment by loki4u** [comment]
change the targetSdkVersion as follows
`<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />`

OR 

handle runtime permission in android using programatically
