### ISSUE TITLE
Question - cannot read property 'scan' of undefined

### ISSUE THREAD

**Issue by uoroaix** [tjwoon/csZBar#76]
Hi
I been trying to use this with ionic framework on top of it with angular. And I am test running the code on my Android. Whenever I try to call the cloudSky.ZBar.scan function I get the following error

```
14    050389   error    TypeError: Cannot read property 'scan' of undefined
    at Scope.$scope.scan2 (http://192.168.1.62:8100/js/controllers.js:29:18)
    at fn (eval at compile (http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:26457:15), <anonymous>:4:206)
    at http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:62386:9
    at Scope.$eval (http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:29158:28)
    at Scope.$apply (http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:29257:23)
    at HTMLButtonElement.<anonymous> (http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:62385:13)
    at HTMLButtonElement.eventHandler (http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:16583:21)
    at triggerMouseEvent (http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:2948:7)
    at tapClick (http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:2937:3)
    at HTMLDocument.tapTouchEnd (http://192.168.1.62:8100/lib/ionic/js/ionic.bundle.js:3064:5)
```

I simply have a function inside my ionic controller like this
```
  $scope.scan2 = function(){
    cloudSky.ZBar.scan({}, 
      function(succcess){ 
        alert(success);
      }, 
      function(error){
        alert(error);
      }
    );  
  }
```
It's telling ZBar is not defined, I was just wondering if I need to import ZBar somewhere or do something to require ZBar?

**Comment by jjbridges** [comment]
Could it be a simple as your capital "Z".  Scanning is performed as:
`cloudSky.zBar.scan(params, onSuccess, onFailure)`
with a lowercase z.
Otherwise check your object in a debugger and see if cloudSky is defined and troubleshoot from there.

**Comment by dcousens** [comment]
How did you go @uoroaix?

**Comment by uoroaix** [comment]
Yes, I was able to compile it on my iphone and it worked with zBar. I
wonder why I didn't even notice it in the first place. Feels dumb now lol.
Thx for the reply and the library, this scanner is by far, way faster than
the one cordova provided.

2016-07-28 18:14 GMT-07:00 Daniel Cousens <notifications@github.com>:

**Comment by dcousens** [comment]
Great to hear!
