### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by picassohoang** [tjwoon/csZBar#95]
When scan qr code with a Landscape oriented app:

11-16 16:20:35.260 24332-24332/com.mobile.bounceoff.kiosk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.mobile.bounceoff.kiosk, PID: 24332
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setDisplayOrientation(int)' on a null object reference
                                                                                at org.cloudsky.cordovaPlugins.ZBarScannerActivity.setCameraDisplayOrientation(ZBarScannerActivity.java:247)
                                                                                at org.cloudsky.cordovaPlugins.ZBarScannerActivity.tryStartPreview(ZBarScannerActivity.java:525)
                                                                                at org.cloudsky.cordovaPlugins.ZBarScannerActivity.surfaceChanged(ZBarScannerActivity.java:301)
                                                                                at android.view.SurfaceView.updateWindow(SurfaceView.java:740)
                                                                                at android.view.SurfaceView.setFrame(SurfaceView.java:386)
                                                                                at android.view.View.layout(View.java:17989)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                at android.view.View.layout(View.java:17993)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                at android.view.View.layout(View.java:17993)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                at android.view.View.layout(View.java:17993)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3172)
                                                                                at android.view.View.layout(View.java:17993)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5817)
                                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2759)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2460)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1528)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7524)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:622)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
11-16 16:20:35.260 3452-4838/? W/ActivityManager:   Force finishing activity com.mobile.bounceoff.kiosk/.MainActivity

**Comment by chinh106x** [comment]
I also face the same issue as @picassohoang 
Is this issue fixed?
